#!/bin/sh
# This file was automatically generated on Wed 25 Jan 2023 13:10:38 GMT from
# source: /dls_sw/work/common/hir12111/src/AD/ADExternal/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi


exec ./example stexample.boot
